//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SucursalAudio {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class configAudio : global::System.Configuration.ApplicationSettingsBase {
        
        private static configAudio defaultInstance = ((configAudio)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new configAudio())));
        
        public static configAudio Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ftp_usarPasivo {
            get {
                return ((bool)(this["ftp_usarPasivo"]));
            }
            set {
                this["ftp_usarPasivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("elisa")]
        public string ftp_usuario {
            get {
                return ((string)(this["ftp_usuario"]));
            }
            set {
                this["ftp_usuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("elisahome")]
        public string ftp_pass {
            get {
                return ((string)(this["ftp_pass"]));
            }
            set {
                this["ftp_pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.25")]
        public string ip_local {
            get {
                return ((string)(this["ip_local"]));
            }
            set {
                this["ip_local"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pruebaelisa.laboratorioschontalpa.com.mx")]
        public string ftp_direccion {
            get {
                return ((string)(this["ftp_direccion"]));
            }
            set {
                this["ftp_direccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("187.157.4.94")]
        public string ip_remota {
            get {
                return ((string)(this["ip_remota"]));
            }
            set {
                this["ip_remota"] = value;
            }
        }
    }
}
